# Config file for automatic testing at travis-ci.org
# Conda testing for Travis CI from https://gist.github.com/dan-blanchard/7045057
language: python

# Will not actually use Python 2.7 installed on the Travis CI server
# but leave this as a reminder of which versions are being tested
python:
  - 2.7

notifications:
  email: false

# Setup Anaconda and xgboost
before_install:
  # Install Anaconda, default Miniconda is Python 2 based
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod u+x miniconda.sh
  # Install Miniconda in batch mode
  - ./miniconda.sh -b  -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  # Install conda distribution of xgboost
  - conda install --yes -c conda-forge xgboost=0.6a2

# Install Python packages
install:
  # Install scikit-learn and pytest for testing
  # xgboost and scikit-learn depend on numpy and scipy so installing
  # scikit-learn first provides the dependencies for xgboost
  - conda install --yes pytest scikit-learn

  # Install rdkit
  - conda install --yes -c omnia rdkit

  # Install lightchem
  - cd ../lightchem
  - pip install -e .

# Run the test functions
script: travis_wait 25 pytest
